version: "3.4"

networks:
  onlineforum-dev:
    driver: bridge

services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    networks:
      - onlineforum-dev

  onlineforum-serv:
    image: forum
    depends_on:
      - "postgres_db"
    ports:
      -  "5000:80"
      - "59164:59164"
    restart: always
    environment:
      DB_CONNECTION_STRING: "Host=postgres_db; Port=5432; Database=ForumDB; User ID=postgres; Password=postgres; Pooling=true;"
    networks:
      - onlineforum-dev

  onlineforum-front:
    image: forum_front
    depends_on:
      - "onlineforum-serv"
    ports:
      - "3000:3000"
    environment:
      API_ROUTE: "http://onlineforum-serv:5000/api"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - './:/app'
      - '/app/node_modules'
    stdin_open: true
    command: npm start
    networks:
      - onlineforum-dev


