export const BEFORE_STATE_POST = "BEFORE_STATE_POST"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_ERROR = "GET_POSTS_ERROR"
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS"
export const POST_CREATE_ERROR = "POST_CREATE_ERROR"
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS"
export const POST_DELETE_ERROR = "POST_DELETE_ERROR"
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS"
export const POST_UPDATE_ERROR = "POST_UPDATE_ERROR"







